try {
  age;
} catch (error) {
  console.log("i am catch block");
  console.log(error.message);
}
/* 
catch block will run if error occur in try block
 */
